apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gixk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gixk
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gixk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gixk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gixk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xlhk-tenant/rhtap-demo-app/hacbs-test-project-gixk@sha256:cc763f16ec36e0eedecfffe09bc148278a3bb3718b37126343196bca3f4352be
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
