apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gixk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xlhk-tenant/rhtap-demo-app/hacbs-test-project-gixk@sha256:2cc5fe40029fc3a55b0a3ff0905af71d1c7c9179ca155c69bbc8632389921c5e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
