apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gixk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xlhk-tenant/rhtap-demo-app/hacbs-test-project-gixk@sha256:cc763f16ec36e0eedecfffe09bc148278a3bb3718b37126343196bca3f4352be
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
